Added a button for story in index,a folder for story in views/admin
at-internship/at-resources-ui pull request #14
Opened 2020-10-28 19:09 UTC by maria201429

…nd the file add-story.hbs with the code of the form to add story

@fasaga

2020-10-29 14:09 UTC, at-internship requested changes
these routes are needed

// AT-RESOURCES - Render Story
router.get("/story", story);

// AT-RESOURCES - Render AddStory
router.get("/story/add", renderAddStoryForm);

// AT-RESOURCES - AddStory
router.post("/story/add", addStory);

2020-10-29 14:09 UTC, at-internship commented on src/views/admin/index.hbs
> +            <tr>
should be
```
<tr>
                <td style="text-align: left;">
                    <a class="btn btn-primary" href="/admin/story">&raquo; Story</a>
                </td>
            </tr>
```

2020-10-29 14:32 UTC, fasaga commented
@at-internship Routes are not part of her task, they will be added by another team member as well as the controller methods, thanks

2020-10-29 19:52 UTC, at-internship approved these changes
Approved

2020-11-02 15:41 UTC, fasaga approved these changes

2020-11-02 15:42 UTC, merged

2020-11-02 15:49 UTC, raaul-at approved these changes