AT-RSC-UI-US16 Admin Module: Delete Story
at-internship/at-resources-ui pull request #15
Opened 2020-11-02 16:28 UTC by Normaillescas29

Admin Module: Delete Story

2020-11-02 17:45 UTC, irvingesp2190 approved these changes

2020-11-02 19:31 UTC, at-internship requested changes

2020-11-02 19:31 UTC, at-internship commented on src/controllers/admin.controller.js
> +    res.redirect("/admin/story");
Add req.flash("success_msg", "Story Deleted Successfully");

2020-11-03 15:37 UTC, at-internship approved these changes
Approved

2020-11-03 15:50 UTC, merged