Added dashboard feature views and sections
at-internship/at-resources-ui pull request #2
Opened 2020-10-15 17:39 UTC by LuisAPerez224

Added dashboard feature views and sections

2020-10-15 20:33 UTC, irvingesp2190 approved these changes

2020-10-16 14:09 UTC, at-internship requested changes

2020-10-16 14:09 UTC, at-internship commented on package.json
> +        "nodemon": "^2.0.5",
why this update?

2020-10-16 14:09 UTC, at-internship commented on src/controllers/at-resources.controller.js
> +// AT-SSO - Admin - Dashboard - Render Add User Form
Should be  `// AT-RESOURCES - Task - Render Add Task Form`

2020-10-16 14:09 UTC, at-internship commented on src/routes/at-resources.routes.js
> +router.get('/', renderDashboard);
Please add code comments for every route like `// AT-RESOURCES - Dashboard`

2020-10-16 14:09 UTC, at-internship commented on src/routes/at-resources.routes.js
> +router.get("/task/add", renderAddTaskForm);
`// AT-RESOURCES - Task - Add Task Form`

2020-10-16 14:09 UTC, at-internship commented on src/routes/at-resources.routes.js
> +router.post("/task/add", addTask);
`// AT-RESOURCES - Task - Add`

2020-10-16 14:09 UTC, at-internship commented on src/routes/at-resources.routes.js
> +router.get("/task/edit/:id", renderEditTaskForm);
`// AT-RESOURCES - Render Edit Task Form`

2020-10-16 14:09 UTC, at-internship commented on src/views/partials/menu-at-resources.hbs
> +        <a class="nav-link" href="/at-resources/dashboard">
shoulde be `<a class="nav-link" href="/dashboard">`

2020-10-16 14:09 UTC, at-internship commented on src/views/partials/menu-at-resources.hbs
> +        <a class="nav-link" href="/at-resources/backlog">
shoulde be `<a class="nav-link" href="/backlog">`

2020-10-16 14:09 UTC, at-internship commented on src/views/partials/menu-at-resources.hbs
> +        <a class="nav-link" href="/at-resources/activeSprint">
shoulde be `<a class="nav-link" href="/sprint">`

2020-10-16 14:09 UTC, at-internship commented on src/views/partials/menu-at-resources.hbs
> +        <a class="nav-link" href="#">
shoulde be `<a class="nav-link" href="/members">`

2020-10-16 14:09 UTC, at-internship commented on src/views/partials/menu-at-resources.hbs
> +        <a class="nav-link" href="#">
shoulde be `<a class="nav-link" href="/teams">`

2020-10-16 14:09 UTC, at-internship commented on src/views/partials/menu-at-resources.hbs
> +        <a class="nav-link" href="#">
shoulde be `<a class="nav-link" href="/mentors">`

2020-10-16 14:09 UTC, at-internship commented on src/views/partials/menu-at-resources.hbs
> +        <a class="nav-link" href="#">
shoulde be `<a class="nav-link" href="/metrics">`

2020-10-16 14:09 UTC, at-internship commented on src/views/partials/menu-at-resources.hbs
> +<!-- REPORTS -->
Remove this section

2020-10-16 17:10 UTC, at-internship commented
This pull must be merged into develop not feature/AT-RSC-UI_Migration

2020-10-16 18:06 UTC, at-internship approved these changes
Approved

2020-10-19 15:02 UTC, merged