US-UI-RE-015 AT-RSC-UI Admin Module: Edit Story and creation of user …
at-internship/at-resources-ui pull request #21
Opened 2020-11-05 19:26 UTC by Antonio-Mendez

…story update method

2020-11-05 21:24 UTC, irvingesp2190 approved these changes

2020-11-05 23:03 UTC, at-internship requested changes

2020-11-05 23:03 UTC, at-internship commented on package.json
> +        "npm-check-updates": "^9.2.4"
why did you increase the version?

2020-11-06 15:35 UTC, Antonio-Mendez commented on package.json
> +        "npm-check-updates": "^9.2.4"
I already updated the versions

2020-11-06 15:42 UTC, at-internship approved these changes
Approved

2020-11-06 15:48 UTC, merged