Feature/at rsc ui unit test/code coverage
at-internship/at-resources-ui pull request #26
Opened 2020-11-27 19:39 UTC by maria201429

@LuisAT07 @Efcobr-AT @Yairmar

2020-11-27 19:45 UTC, at-internship requested changes

2020-11-27 19:45 UTC, at-internship commented on src/test/controllers/admin.controller.test.js
> + * AT UNIVERSITY UI - AT Admin Controller Test.
AT RESOURCES UI

2020-11-27 19:45 UTC, at-internship commented on src/test/controllers/admin.controller.test.js
> +const adminC = require("../../controllers/admin.controller");
const adminController

2020-11-27 19:45 UTC, at-internship commented on src/test/services/at-resources.service.test.js
> + * AT UI MOCKS - AT University Service API Test.
AT RESOURCES UI

2020-11-27 19:45 UTC, at-internship commented on src/test/services/at-resources.service.test.js
> + * Integration Test for at-university-api endpoint.
Integration Test for at-resources-api endpoint.

2020-11-27 19:45 UTC, at-internship commented on src/test/services/at-resources.service.test.js
> +// AT University Service API
AT Resources Service API

2020-11-27 19:49 UTC, at-internship commented on src/test/services/at-resources.service.test.js
> + * Integration Test for at-university-api endpoint.
AT RESOURCES UI - AT Resources Service API Test.

2020-11-27 19:53 UTC, Yairmar approved these changes

2020-11-27 19:57 UTC, at-internship commented on package.json
>          "connect-flash": "^0.1.1",
chai-http dependency is missing "chai-http": "^4.3.0",

2020-12-04 15:23 UTC, LuisAT07 approved these changes

2020-12-04 19:20 UTC, at-internship approved these changes
Approved

2020-12-04 19:20 UTC, merged