feature/AT-RSC-UI-Backlog added backlog section and views
at-internship/at-resources-ui pull request #5
Opened 2020-10-19 16:13 UTC by Antonio-Mendez

2020-10-19 16:33 UTC, irvingesp2190 approved these changes

2020-10-19 20:28 UTC, at-internship requested changes

2020-10-19 20:28 UTC, at-internship commented on src/routes/at-resources.routes.js
> +        renderBacklog,} = require("../controllers/at-resources.controller");
shpould be `renderBacklog} = require("../controllers/at-resources.controller");`

2020-10-19 20:28 UTC, at-internship commented on src/controllers/at-resources.controller.js
> +// AT-RESOURCES - Index/Backlog
// AT-RESOURCES - Backlog

2020-10-21 14:31 UTC, at-internship approved these changes

2020-10-21 15:07 UTC, merged